name: pyssem
on:
  push:
    branches:
      - pypi-release
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build and publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__  # Use this for PyPI API tokens
          password: ${{ secrets.PYPI_API_TOKEN }}
          # If your project uses dist/, you might need to add `packages-dir: dist`

      - name: Install the package (optional, for testing after publishing)
        run: pip install pyssem
